### ISSUE TITLE
textacy not working

### ISSUE THREAD

**Issue by guillim** [theashworld/nlp_on_aws_lambda#1]
Hello,

Thanks for your post, it was very helpful for me. I manage to use spacy and many libraries, but textacy I cannot. How did you manage to get it work (like the title of your article suggests) ?

I have this error while trying to use textacy on the AWS lambda console
> [ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': No module named 'spacy.lang.xx' 

Any suggestion will be welcome !

**Comment by theashworld** [comment]
hi guillim with the new capabilities recently introduced in lambda, I think you can just make a Docker image and that should serve you better. Refer - https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/

But if you can't use that for some reason, this approach does work for us, I have published a release https://github.com/theashworld/nlp_on_aws_lambda/releases/tag/v1 which is the .zip we use, that should work for you too.
